/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LegalAccountDeletionRouteImport } from './routes/legal.account-deletion'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as LegalRefundRouteImport } from './routes/legal.refund'
import { Route as LegalSellerAgreementRouteImport } from './routes/legal.seller-agreement'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as ManufacturerFashionRouteImport } from './routes/manufacturer.fashion'
import { Route as ManufacturerFmcgRouteImport } from './routes/manufacturer.fmcg'
import { Route as RetailerFashionRouteImport } from './routes/retailer.fashion'
import { Route as RetailerFmcgRouteImport } from './routes/retailer.fmcg'
import { Route as ShopFashionRouteImport } from './routes/shop.fashion'
import { Route as ShopFmcgRouteImport } from './routes/shop.fmcg'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalAccountDeletionRoute = LegalAccountDeletionRouteImport.update({
  id: '/legal/account-deletion',
  path: '/legal/account-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRefundRoute = LegalRefundRouteImport.update({
  id: '/legal/refund',
  path: '/legal/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSellerAgreementRoute = LegalSellerAgreementRouteImport.update({
  id: '/legal/seller-agreement',
  path: '/legal/seller-agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerFashionRoute = ManufacturerFashionRouteImport.update({
  id: '/manufacturer/fashion',
  path: '/manufacturer/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturerFmcgRoute = ManufacturerFmcgRouteImport.update({
  id: '/manufacturer/fmcg',
  path: '/manufacturer/fmcg',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerFashionRoute = RetailerFashionRouteImport.update({
  id: '/retailer/fashion',
  path: '/retailer/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const RetailerFmcgRoute = RetailerFmcgRouteImport.update({
  id: '/retailer/fmcg',
  path: '/retailer/fmcg',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopFashionRoute = ShopFashionRouteImport.update({
  id: '/shop/fashion',
  path: '/shop/fashion',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopFmcgRoute = ShopFmcgRouteImport.update({
  id: '/shop/fmcg',
  path: '/shop/fmcg',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/manufacturer/fashion': typeof ManufacturerFashionRoute
  '/manufacturer/fmcg': typeof ManufacturerFmcgRoute
  '/retailer/fashion': typeof RetailerFashionRoute
  '/retailer/fmcg': typeof RetailerFmcgRoute
  '/shop/fashion': typeof ShopFashionRoute
  '/shop/fmcg': typeof ShopFmcgRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/manufacturer/fashion': typeof ManufacturerFashionRoute
  '/manufacturer/fmcg': typeof ManufacturerFmcgRoute
  '/retailer/fashion': typeof RetailerFashionRoute
  '/retailer/fmcg': typeof RetailerFmcgRoute
  '/shop/fashion': typeof ShopFashionRoute
  '/shop/fmcg': typeof ShopFmcgRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/legal/account-deletion': typeof LegalAccountDeletionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/refund': typeof LegalRefundRoute
  '/legal/seller-agreement': typeof LegalSellerAgreementRoute
  '/legal/terms': typeof LegalTermsRoute
  '/manufacturer/fashion': typeof ManufacturerFashionRoute
  '/manufacturer/fmcg': typeof ManufacturerFmcgRoute
  '/retailer/fashion': typeof RetailerFashionRoute
  '/retailer/fmcg': typeof RetailerFmcgRoute
  '/shop/fashion': typeof ShopFashionRoute
  '/shop/fmcg': typeof ShopFmcgRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/legal/account-deletion'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/manufacturer/fashion'
    | '/manufacturer/fmcg'
    | '/retailer/fashion'
    | '/retailer/fmcg'
    | '/shop/fashion'
    | '/shop/fmcg'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/legal/account-deletion'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/manufacturer/fashion'
    | '/manufacturer/fmcg'
    | '/retailer/fashion'
    | '/retailer/fmcg'
    | '/shop/fashion'
    | '/shop/fmcg'
  id:
    | '__root__'
    | '/'
    | '/legal/account-deletion'
    | '/legal/privacy'
    | '/legal/refund'
    | '/legal/seller-agreement'
    | '/legal/terms'
    | '/manufacturer/fashion'
    | '/manufacturer/fmcg'
    | '/retailer/fashion'
    | '/retailer/fmcg'
    | '/shop/fashion'
    | '/shop/fmcg'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LegalAccountDeletionRoute: typeof LegalAccountDeletionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRefundRoute: typeof LegalRefundRoute
  LegalSellerAgreementRoute: typeof LegalSellerAgreementRoute
  LegalTermsRoute: typeof LegalTermsRoute
  ManufacturerFashionRoute: typeof ManufacturerFashionRoute
  ManufacturerFmcgRoute: typeof ManufacturerFmcgRoute
  RetailerFashionRoute: typeof RetailerFashionRoute
  RetailerFmcgRoute: typeof RetailerFmcgRoute
  ShopFashionRoute: typeof ShopFashionRoute
  ShopFmcgRoute: typeof ShopFmcgRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/account-deletion': {
      id: '/legal/account-deletion'
      path: '/legal/account-deletion'
      fullPath: '/legal/account-deletion'
      preLoaderRoute: typeof LegalAccountDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/refund': {
      id: '/legal/refund'
      path: '/legal/refund'
      fullPath: '/legal/refund'
      preLoaderRoute: typeof LegalRefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/seller-agreement': {
      id: '/legal/seller-agreement'
      path: '/legal/seller-agreement'
      fullPath: '/legal/seller-agreement'
      preLoaderRoute: typeof LegalSellerAgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer/fashion': {
      id: '/manufacturer/fashion'
      path: '/manufacturer/fashion'
      fullPath: '/manufacturer/fashion'
      preLoaderRoute: typeof ManufacturerFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturer/fmcg': {
      id: '/manufacturer/fmcg'
      path: '/manufacturer/fmcg'
      fullPath: '/manufacturer/fmcg'
      preLoaderRoute: typeof ManufacturerFmcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/fashion': {
      id: '/retailer/fashion'
      path: '/retailer/fashion'
      fullPath: '/retailer/fashion'
      preLoaderRoute: typeof RetailerFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retailer/fmcg': {
      id: '/retailer/fmcg'
      path: '/retailer/fmcg'
      fullPath: '/retailer/fmcg'
      preLoaderRoute: typeof RetailerFmcgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/fashion': {
      id: '/shop/fashion'
      path: '/shop/fashion'
      fullPath: '/shop/fashion'
      preLoaderRoute: typeof ShopFashionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/fmcg': {
      id: '/shop/fmcg'
      path: '/shop/fmcg'
      fullPath: '/shop/fmcg'
      preLoaderRoute: typeof ShopFmcgRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LegalAccountDeletionRoute: LegalAccountDeletionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRefundRoute: LegalRefundRoute,
  LegalSellerAgreementRoute: LegalSellerAgreementRoute,
  LegalTermsRoute: LegalTermsRoute,
  ManufacturerFashionRoute: ManufacturerFashionRoute,
  ManufacturerFmcgRoute: ManufacturerFmcgRoute,
  RetailerFashionRoute: RetailerFashionRoute,
  RetailerFmcgRoute: RetailerFmcgRoute,
  ShopFashionRoute: ShopFashionRoute,
  ShopFmcgRoute: ShopFmcgRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
